---
abstract: 'DBI SQL abstraction'
author:
  - 'Rebecca Turner <me@re-becca.org>'
build_requires:
  DBD::SQLite: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.011, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Abstract
requires:
  Check::ISA: 0
  DBI: 0
  Scalar::Util: 0
resources:
  bugtracker: https://github.com/iarna/DBIx-Abstract/issues
  homepage: https://github.com/iarna/DBIx-Abstract
  repository: https://github.com/iarna/DBIx-Abstract.git
version: 1.02
